#!/bin/bash

mkdir ../../synth_results
mkdir ../../synth_results/energy_plot
mkdir ../../synth_results/synth_raw
mkdir ../../synth_results/synth_raw/split

mkdir ../../rat_II_synth/mat_inv
mkdir ../../rat_II_synth/mat_inv/UniformILPNew
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_8_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_21_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_22_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_28_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_33_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_35_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_49_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_55_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_72_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_99_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_116_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_120_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_128_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_135_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_150_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_161_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_164_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_170_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_175_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_185_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_194_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/UniformILPNew/mat_inv_UniformILPNew_197_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_13_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_23_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_24_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_37_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_46_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_74_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_90_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_110_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_117_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_129_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_136_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_151_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_154_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_162_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_165_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_187_ultrascale2_250
mkdir ../../rat_II_synth/mat_inv/NonUniformILP/mat_inv_NonUniformILP_195_ultrascale2_250
mkdir ../../rat_II_synth/r2_FFT
mkdir ../../rat_II_synth/r2_FFT/UniformILPNew
mkdir ../../rat_II_synth/r2_FFT/UniformILPNew/UniformILPNew_41_ultrascale2_250
mkdir ../../rat_II_synth/r2_FFT/UniformILPNew/UniformILPNew_199_ultrascale2_250
mkdir ../../rat_II_synth/r2_FFT/NonUniformILP
mkdir ../../rat_II_synth/r2_FFT/NonUniformILP/UniformILPNew_43_ultrascale2_250
mkdir ../../rat_II_synth/r2_FFT/NonUniformILP/UniformILPNew_70_ultrascale2_250
mkdir ../../rat_II_synth/r2_FFT/NonUniformILP/UniformILPNew_112_ultrascale2_250
mkdir ../../rat_II_synth/r2_FFT/NonUniformILP/UniformILPNew_189_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_1_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_2_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_3_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_4_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_5_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_6_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_7_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_8_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_9_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_10_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_11_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_12_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_13_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_14_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_15_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_16_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_17_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_18_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_19_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_20_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_21_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_22_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_23_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_24_ultrascale2_250
mkdir ../../int_II_synth/r2_FFT/r2_FFT_ED97_25_ultrascale2_250
